-- Clean existing deeds
delete from deeds;

-- Insert 52 seed deeds (first person, past tense, varied length)
insert into deeds (content, author, status, expires_at) values
('Let my first check of the year go to a local food bank.', 'Anonymous', 'approved', now() + interval '30 days'),
('Helped a friend move to her new apartment without being asked.', 'Sarah', 'approved', now() + interval '30 days'),
('Volunteered for two hours at the animal shelter down the street.', 'Anonymous', 'approved', now() + interval '30 days'),
('Unplugged all my devices before leaving for the weekend.', 'Marco', 'approved', now() + interval '30 days'),
('Bought flowers for my grandmother just to see her smile.', 'Anonymous', 'approved', now() + interval '30 days'),
('Let a driver merge into my lane even though I was in a rush.', 'James', 'approved', now() + interval '30 days'),
('Wrote a thank-you note to my old teacher who shaped who I am.', 'Anonymous', 'approved', now() + interval '30 days'),
('Found a box of things I no longer need and donated them.', 'Elena', 'approved', now() + interval '30 days'),
('Planted a tree in the park near my house.', 'Anonymous', 'approved', now() + interval '30 days'),
('Played guitar at a local nursing home for an hour.', 'Tom', 'approved', now() + interval '30 days'),
('Taught my 74-year-old neighbor how to video call her grandchildren.', 'Anonymous', 'approved', now() + interval '30 days'),
('Organised a Sunday lunch and brought my whole family together.', 'Maria', 'approved', now() + interval '30 days'),
('Collected old toys from friends and brought them to a children''s ward.', 'Anonymous', 'approved', now() + interval '30 days'),
('Stopped everything for ten minutes and just looked at the sky.', 'Anonymous', 'approved', now() + interval '30 days'),
('Found a coat I never wore and left it at a shelter.', 'Luca', 'approved', now() + interval '30 days'),
('Donated my old phone to a programme that refurbishes devices for elderly people.', 'Anonymous', 'approved', now() + interval '30 days'),
('Printed double-sided all day at work. Small, but it adds up.', 'Anonymous', 'approved', now() + interval '30 days'),
('Cooked a lasagne for my neighbour who just had a baby.', 'Rosa', 'approved', now() + interval '30 days'),
('Took five minutes to count three things I am genuinely grateful for.', 'Anonymous', 'approved', now() + interval '30 days'),
('Signed up for a CPR course starting next month.', 'David', 'approved', now() + interval '30 days'),
('Started a small vegetable garden on my balcony. The tomatoes are for the food bank.', 'Anonymous', 'approved', now() + interval '30 days'),
('Collected old suitcases from friends to donate to children in foster care.', 'Anonymous', 'approved', now() + interval '30 days'),
('Added myself to the bone marrow registry. It costs nothing and could save a life.', 'Mia', 'approved', now() + interval '30 days'),
('Picked up litter on my morning walk without telling anyone.', 'Anonymous', 'approved', now() + interval '30 days'),
('Spent an afternoon reading stories to residents at a retirement home.', 'Anonymous', 'approved', now() + interval '30 days'),
('Donated blood. The nurse said it was enough for three people.', 'Alex', 'approved', now() + interval '30 days'),
('Turned off every light in the office before I left. First time in years.', 'Anonymous', 'approved', now() + interval '30 days'),
('Started a folder of news stories about people doing good. Already full.', 'Anonymous', 'approved', now() + interval '30 days'),
('Decided to listen more and talk less. Working on it.', 'Chris', 'approved', now() + interval '30 days'),
('Called an old friend and apologised for something I said years ago.', 'Anonymous', 'approved', now() + interval '30 days'),
('Brought homemade soup to the new family that moved in next door.', 'Giulia', 'approved', now() + interval '30 days'),
('Signed up to help adults learn to read at the local library.', 'Anonymous', 'approved', now() + interval '30 days'),
('Put together a bag of school supplies and left it at the community centre.', 'Anonymous', 'approved', now() + interval '30 days'),
('Collected hotel toiletries all year and finally donated them to a women''s shelter.', 'Anonymous', 'approved', now() + interval '30 days'),
('Sent my old glasses to an organisation that sends them to people in need.', 'Nina', 'approved', now() + interval '30 days'),
('Took a colleague out for lunch. She''d been having a rough week.', 'Anonymous', 'approved', now() + interval '30 days'),
('Finally returned a call I had been putting off for three weeks.', 'Anonymous', 'approved', now() + interval '30 days'),
('Set up a monthly donation to a cause I believe in.', 'Sam', 'approved', now() + interval '30 days'),
('Spent a Saturday morning volunteering at the soup kitchen.', 'Anonymous', 'approved', now() + interval '30 days'),
('Made a point of answering every call with a smile in my voice today.', 'Anonymous', 'approved', now() + interval '30 days'),
('Took everything recyclable to the right bins. All of it.', 'Leo', 'approved', now() + interval '30 days'),
('Organised a charity lunch at work. We collected enough for fifty meals.', 'Anonymous', 'approved', now() + interval '30 days'),
('Turned off the tap every time I brushed my teeth. All day.', 'Anonymous', 'approved', now() + interval '30 days'),
('Left the car at home and took the bus. The long way round.', 'Anonymous', 'approved', now() + interval '30 days'),
('Adopted a rescue dog named Peanut. We are both very happy.', 'Vera', 'approved', now() + interval '30 days'),
('Made a double batch of chili and left half with my elderly neighbour.', 'Anonymous', 'approved', now() + interval '30 days'),
('Replaced every light bulb at home with energy-efficient ones. Finally.', 'Anonymous', 'approved', now() + interval '30 days'),
('Asked my father how his day was and actually sat down to listen.', 'Anonymous', 'approved', now() + interval '30 days'),
('Held the door open for seven strangers in a row. Counted.', 'Anonymous', 'approved', now() + interval '30 days'),
('Praised a colleague''s work in front of the whole team. She deserved it.', 'Anonymous', 'approved', now() + interval '30 days'),
('Sat quietly for ten minutes. Nothing. Just breathed.', 'Anonymous', 'approved', now() + interval '30 days'),
('Bought an extra tin of food at the supermarket and left it at the collection point.', 'Anonymous', 'approved', now() + interval '30 days');
